Your_age = input("please, Enter your age: ")
print(Your_age)
Your_name = input("please, Enter your name: ")
print(Your_name)
Your_birthday = input("please, Enter your birthday: ")
print(Your_birthday)
Your_favorite_hobby = input("please,  Enter your hobby: ")
print(Your_favorite_hobby)
Your_city = input("Please, Enter your city/country: ")
print(Your_city)
Your_browser = input("Please, Enter your browser : ")
print(Your_browser)
Your_Windows = input("Please, Enter your Windows : ")
print(Your_Windows)