import turtle
k = turtle.Turtle()
wn = turtle.Screen()
k.color("yellow")
wn.bgcolor("black")
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(150)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(150)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(150)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(250)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(250)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(250)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(350)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(350)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(350)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(450)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(450)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(90)
k.forward(450)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(120)
k.forward(550)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()
k.penup()
k.left(120)
k.forward(550)
k.pendown()
k.begin_fill()
for i in range(5):
    k.forward(50)
    k.right(144)
k.end_fill()