import turtle

t = turtle.Turtle()
l = turtle.Turtle()
d = turtle.Turtle()
s = turtle.Turtle()
a = turtle.Turtle()
w = turtle.Turtle()
t.forward(150)
l.backward(200)
d.left(150)
d.forward(150)
s.right(150)
s.forward(200)
a.left(50)
a.forward(150)
w.right(50)
w.forward(200)

r = t.distance(l)
p = l.distance(d)
i = d.distance(t)
s = s.distance(t)
a = s.distance(l)
x = s.distance(d)
print(r)
print(p)
print(i)
print(s)
print(a)
print(x)