# Indexing (Access single Item)
mystring = "I love python"
print(mystring[0])
print(mystring[2])
print(mystring[3])
print(mystring[4])
print(mystring[5])
print(mystring[6])
print(mystring[7])
print(mystring[8])
print(mystring[9])
print(mystring[-1])
print(mystring[-2])
print(mystring[-3])
print(mystring[-4])
print(mystring[-5])
print(mystring[-6])
print(mystring[-7])
print(mystring[-8])
print(mystring[-9])

# slicing (Access Multiple squence Items ) [start:End] [start:End:steps]
print(mystring[1:2])
print(mystring[1:3])
print(mystring[1:4])
print(mystring[1:5])
print(mystring[1:6])
print(mystring[1:7])
print(mystring[1:8])
print(mystring[1:9])
print(mystring[1:10])
print(mystring[1:11])
print(mystring[1:12])
print(mystring[1:13])

print(mystring[:1])
print(mystring[:2])
print(mystring[:3])
print(mystring[:4])
print(mystring[:5])
print(mystring[:6])
print(mystring[:7])
print(mystring[:8])
print(mystring[:9])
print(mystring[:10])
print(mystring[:11])
print(mystring[:12])
print(mystring[:13])

print(mystring[:])  # full DATA

print(mystring[0::1])  # full data
print(mystring[::1])  # full data
print(mystring[::2])
print(mystring[::3])
